# está application.properties o application.yml
spring:
  application:
    name: por-hacer
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    #Nomnre de la tabla en la base de datos h2
    url: "jdbc:h2:mem:porhacerapp;DB_CLOSE_ON_EXIT=FALSE"
    #Se habilita la consola h2, permite visualizar en la bd los elementos que vamos guardando
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

    #Cuando la app arranca crea nuevamente nuestras tablas
    hibernate:
      ddl-auto: create-drop